name: truck_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0-90.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  path_provider: ^2.1.2
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  carousel_slider: ^4.2.1
  sks_ticket_view: ^1.0.0
  url_launcher: ^6.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  google_fonts: ^6.2.1
  intl: ^0.17.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/Images/
